---
title: "Consensus clustering and sources of variation"
author: Beata Szeitz
output:
  html_notebook:
    toc: yes
---

# Load packages, functions and files

```{r }
# R vs.4.2.0
source("Load_packages.R")
source("Utility_functions.R")
source("Color_list.R")
```

```{r }
Annot <- read_in_with_rowname("Files/Annotation",F)
row.names(Annot) <- Annot$Sample
Scores <- read_in_with_rowname("Files/NE_EMT_scores",F)
Annot <- merge(Annot, Scores[,c("Sample", "NEscore", "EMTscore")], by="Sample")
CP.expr.imp <- read_in_with_rowname("Files/CP_expression_filtered_imputed",F)[,Annot$Sample]
CM.expr.imp <- read_in_with_rowname("Files/CM_expression_filtered_imputed",F)[,Annot$Sample]
Secreted.proteins <- read_in_with_rowname("Files/Tier1_and_2_secreted",F)[,1]
CM.expr.imp.secr <- CM.expr.imp[row.names(CM.expr.imp) %in% Secreted.proteins,]
```


```{r }
mean(apply(read_in_with_rowname("Files/CP_expression_full",F), 1, sd, na.rm=TRUE), na.rm=T)
mean(apply(read_in_with_rowname("Files/CM_expression_full",F), 1, sd, na.rm=TRUE), na.rm=T)

```


# Filter by SD


```{r }
SD.CP.imp <- apply(CP.expr.imp, 1, sd, na.rm=TRUE)
CP.expr.imp.sd <- CP.expr.imp[SD.CP.imp > 1.25,]

SD.CM.imp <- apply(CM.expr.imp, 1, sd, na.rm=TRUE)
CM.expr.imp.sd <- CM.expr.imp[SD.CM.imp > 1.25,]
```


```{r }
CP.expr.imp.sd.scaled <- t(scale(t(CP.expr.imp.sd)))
CM.expr.imp.sd.scaled <- t(scale(t(CM.expr.imp.sd)))

```


# PVCA and PCA plots


```{r PVCAs, fig.width = 8, fig.height = 4}
annot.columns <- c("Subtype", 
                   "Culture type")
annot.pvca <- Annot[,annot.columns]
colnames(annot.pvca) <- c("Subtype", "Culture.type")

PVCA.CP <- plot_PVCA(as.data.frame(CP.expr.imp.sd), Annot, "Sample", 
          annot.columns, pct.threshold = 0.6, color="blue", 
          "", F)
PVCA.CP$Data <- "CP"
PVCA.CM <- plot_PVCA(as.data.frame(CM.expr.imp.sd.scaled), Annot, "Sample", 
          annot.columns, pct.threshold = 0.6, color="blue", 
          "", F)
PVCA.CM$Data <- "CM"

PVCA.CP.CM <- rbind(PVCA.CP, PVCA.CM)
PVCA.CP.CM$Data <- factor(PVCA.CP.CM$Data, levels = c("CP","CM"))

```

```{r , fig.width = 6, fig.height = 4}
ggplot(PVCA.CP.CM, aes(x=label, y=dat,fill=Data)) + ggtitle("SD > 1.25") + geom_bar(stat="identity", position=position_dodge())+
  scale_x_discrete(limits=PVCA.CP$label)+ scale_fill_manual(values=c("darkgrey","lightblue"))+
  scale_y_continuous(limits = c(0,0.65))+labs(x= "Effects", y= "Weighted avr. proportion var.")+ 
  theme_classic()+theme(legend.position="bottom")
```


```{r }
culture.type <- Annot$`Culture type`
CP.PCA <- ggbiplot(prcomp(t(na.omit(CP.expr.imp.sd.scaled))), 
                   choices= c(1,2),
                   var.axes=FALSE, 
                   #labels=Annot$To.label,
                   groups=Annot$Subtype,
                   labels.size = 3,
                   ellipse=T,
                   ellipse.prob = 0.95,
                   circle=F)  + theme_bw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  geom_abline(intercept = 1.2, slope = -4, color="black", 
              linetype="dashed", size=1.5) +
  annotate("text", x=0.8, y=2.1, label= "Susp/Semi-Adh",fontface =2, color="black")+
  annotate("text", x=-0.8, y=2.1, label= "Adh",fontface =2, color="black")+ggtitle("CP (SD > 1.25)")+ 
  #annotate("text", x=-0.45, y=-0.55, label= "H1048",fontface =2, color="red")+
  annotate("text", x=-0.85, y=-1.0, label= "H1882",fontface =2, color="red")+
  annotate("text", x=-0.15, y=-2.1, label= "H1688",fontface =2, color="red")+
  annotate("text", x=-0.1, y=-2.35, label= "DMS53",fontface =2, color="red")+
  geom_point(aes(shape=culture.type, color=Annot$Subtype), size=3)+scale_shape_manual(values=c(16, 8, 15))+
  scale_color_manual(values=c("#0000FE","#21FE06","gold","#FB02FE")) 

CP.PCA
CM.secr.PCA <- ggbiplot(prcomp(t(na.omit(CM.expr.imp.sd.scaled))), 
                        choices= c(1,2),
                        var.axes=FALSE, 
                        #labels=Annot$Name,
                        groups=Annot$Subtype,
                        labels.size = 3,
                        ellipse=F,
                        ellipse.prob = 0.95,
                        circle=F)  + theme_bw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  geom_abline(intercept = -0.5, slope = 2.5, color="black", 
              linetype="dashed", size=1.5) +
  annotate("text",  x=-1.4, y=-2, label= "Susp/Semi-Adh",fontface =2, color="black")+
  annotate("text", x=-0.3, y=-2, label= "Adh",fontface =2,  color="black")+ggtitle("CM (SD > 1.25)")+ 
  geom_point(aes(shape=culture.type, color=Annot$Subtype), size=3)+scale_shape_manual(values=c(16, 8, 15))+
  scale_color_manual(values=c("#0000FE","#21FE06","gold","#FB02FE"))

CM.secr.PCA
```

```{r , fig.width=9, fig.height=5}
ggarrange(CP.PCA+ theme(legend.position = "none"), CM.secr.PCA+ theme(legend.position = "none"), 
          ncol=2, nrow=1)

```

```{r }
save(CP.expr.imp.sd,CM.expr.imp.sd, Annot, file="RData/CP_CM_PCAs_PVCAs.RData")

```



# Consensus clustering

```{r , fig.width=10, fig.height=5}
par(mfrow=c(2,2))
cluster.res <- ConsensusClusterPlus(as.matrix(CP.expr.imp.sd),
                                   maxK=7,
                                   reps=1000,
                                   pItem=0.8,
                                   pFeature=0.8,  
                                   clusterAlg="pam",
                                   finalLinkage = "complete",
                                   innerLinkage = "complete",
                                   distance="pearson",
                                   plot = "pdf",
                                   seed=1262118388.71279)
```


```{r , }
Annot[,"K4"] <- cluster.res[[4]][["consensusClass"]]
Annot[,"K5"] <- cluster.res[[5]][["consensusClass"]]

par(mfrow=c(1,2))
dis = Dist(t(as.matrix(CP.expr.imp.sd)), method = "pearson")
sil = silhouette (cluster.res[[4]][["consensusClass"]], dis, nmax.lab = 30, max.strlen = 10)
plot(sil, main="K=4")
sil = silhouette (cluster.res[[5]][["consensusClass"]], dis, nmax.lab = 30, max.strlen = 10)
plot(sil, main="K=5")

```

```{r , eval=F}
svg(filename="Silhouette_plots.svg", width = 13, height = 8)
par(mfrow=c(1,2))
dis = amap::Dist(t(as.matrix(CP.expr.imp.sd)), method = "pearson")
sil = silhouette (cluster.res[[4]][["consensusClass"]], dis, nmax.lab = 30, max.strlen = 10)
plot(sil, main="K=4")
sil = silhouette (cluster.res[[5]][["consensusClass"]], dis, nmax.lab = 30, max.strlen = 10)
plot(sil, main="K=5")
dev.off()
```


```{r , fig.width=12, fig.height=12}
Annot$Cluster <- paste("Cluster", Annot$K4, sep=" ")
column.ha = HeatmapAnnotation(df =Annot[,c("Subtype", "ASCL1 qPCR", "NEUROD1 qPCR", "POU2F3 qPCR", "YAP1 qPCR",
                                           "Culture type","Cell line origin","Chemo")],
                              which="col",
                              col=colorlist,
                              annotation_name_side = "right",
                              gp = gpar(col = "grey"),
                              "NE score" = anno_barplot(Annot$NEscore,
                                                        gp = gpar(fill =  c("#76069a")),
                                                        height = unit(1.5, "cm"),
                                                        axis_param = list(
                                                          side = "left",
                                                          at = c(-2.25,0,1.5), 
                                                          labels = c("-2.25","0", "+1.5") )),
                              "EMT score" = anno_barplot(Annot$EMTscore,
                                                            gp = gpar(fill =  c("#005757")),
                                                            height = unit(1.5, "cm"),
                                                            axis_param = list(
                                                              side = "left",
                                                              at = c(-1.9,0,1.6), 
                                                              labels = c("-1.9","0", "+1.6") )),
                              gap = unit(c(2,1,1,1,2,1,1,1.5,2), 'mm'),
                              show_legend = TRUE,
                              show_annotation_name = TRUE)
set.seed(12345)
ht = Heatmap(as.matrix(CP.expr.imp.sd.scaled),
                     name="Z-score",
             col=colorRamp2(c(-2, 0,2), c("blue","white","red")),
                     cluster_rows = T, top_annotation = column.ha, 
             column_labels =  Annot$Sample,
             column_split = Annot$Cluster,  
             cluster_columns = T,
             clustering_method_columns = "complete",
             clustering_method_rows = "complete",
             show_row_dend = F,
             show_row_names = F, 
             column_gap = unit(0.1, "cm"),
             column_names_gp = gpar(fontsize = 12),
             #row_split = rowsplits, 
             gap = unit(0.1, "cm"),
             show_heatmap_legend = T,
             show_column_names = T,
             heatmap_width = unit(10, "cm"))
ht = draw(ht, annotation_legend_side="bottom",
             heatmap_legend_side="left")
```


```{r }
Annot.Cluster <- Annot
save(cluster.res, Annot.Cluster, CP.expr.imp.sd.scaled, CP.expr.imp.sd, file= "RData/Fig_consClust.RData")
```


