---
title: "Differential expression analysis with subtype"
author: Beata Szeitz
output:
  html_notebook:
    toc: yes
---

# Load packages, functions and files


```{r }
# R vs.4.2.0
source("Load_packages.R")
source("Utility_functions.R")
source("Color_list.R")
```


```{r }
Annot <- read_in_with_rowname("Files/Annotation",F)
row.names(Annot) <- Annot$Sample
CP.expr.imp <- read_in_with_rowname("Files/CP_expression_filtered_imputed",F)[,Annot$Sample]
CM.expr.imp <- read_in_with_rowname("Files/CM_expression_filtered_imputed",F)[,Annot$Sample]
CP.expr <- read_in_with_rowname("Files/CP_expression_full",F)[,Annot$Sample]
CM.expr <- read_in_with_rowname("Files/CM_expression_full",F)[,Annot$Sample]

Protein.to.gene <- read_in_with_rowname("Files/Protein_to_gene",F)
row.names(Protein.to.gene) <- Protein.to.gene$Protein
Protein.Annot <- read_in_with_rowname("Files/Secreted_surface_plasma_druggable_info",F)
Protein.Annot$Accession <- Protein.Annot$Protein

```


# Differential expression analysis


```{r ,eval=F}
CP.Subtype.ANOVA <- ANOVAandTK_padj_rank(annotation = Annot, colname_for_factor = "Subtype",
                                        levelOrder = c("SCLC-A", "SCLC-N", "SCLC-P", "SCLC-Y"), m = CP.expr.imp)
CM.Subtype.ANOVA <- ANOVAandTK_padj_rank(annotation = Annot, colname_for_factor = "Subtype",
                                        levelOrder = c("SCLC-A", "SCLC-N", "SCLC-P", "SCLC-Y"), m = CM.expr.imp)
save(CP.Subtype.ANOVA, CM.Subtype.ANOVA, file="RData/CP_and_CM_DEA_Subtype.RData")
export_with_rowname(CP.Subtype.ANOVA, "Files/CP_DEA_Subtype", F)
export_with_rowname(CM.Subtype.ANOVA, "Files/CM_DEA_Subtype", F)
```


```{r }
load("RData/CP_and_CM_DEA_Subtype.RData")

```


```{r Load file that contains Entrez IDs for UniProt accession numbers}
UniProt.to.Entrez <- read.delim("Files/UniProt_to_Entrez.txt")
```


# Select subtype-specific proteins

```{r }
Subtype.specific <- list("SCLC-A" = NA, "SCLC-N"= NA, "SCLC-P"= NA, "SCLC-Y"= NA)

#CM.Subtype.ANOVA.SPs["Q99988",]

st <- "SCLC-A"
Subtype.specific <- lapply(names(Subtype.specific), function(st){
  CP.sign <- CP.Subtype.ANOVA[CP.Subtype.ANOVA$`p.adj Subtype` < 0.05,]
  CP.sign$Data <- "CP"
  relevant.columns <- colnames(CP.sign)[grepl("tukey(", colnames(CP.sign), fixed=T)]
  relevant.columns <- relevant.columns[grepl(st, relevant.columns)]
  CP.Anovafilt <- CP.sign[,c("Accession","Data",relevant.columns)]
  CP.Anovafilt <- subset(CP.Anovafilt, CP.Anovafilt[,3] < 0.05 & CP.Anovafilt[,4] < 0.05 & CP.Anovafilt[,5] < 0.05)
  
  CM.sign <- CM.Subtype.ANOVA[CM.Subtype.ANOVA$`p.adj Subtype` < 0.05,]
  CM.sign$Data <- "CM"
  relevant.columns <- colnames(CM.sign)[grepl("tukey(", colnames(CM.sign), fixed=T)]
  relevant.columns <- relevant.columns[grepl(st, relevant.columns)]
  CM.Anovafilt <- CM.sign[,c("Accession","Data",relevant.columns)]
  CM.Anovafilt <- subset(CM.Anovafilt, CM.Anovafilt[,3] < 0.05 & CM.Anovafilt[,4] < 0.05 & CM.Anovafilt[,5] < 0.05)
  
  print(st)
  print(nrow(CP.Anovafilt))
  print(nrow(CM.Anovafilt))
  
  
  ANOVAres <- rbind(CP.sign[CP.sign$Accession %in% CP.Anovafilt$Accession,],
                    CM.sign[CM.sign$Accession %in% CM.Anovafilt$Accession,])
  
  
  
  
  print(any(duplicated(ANOVAres$Accession)))
  
  ANOVAres$Subtype.specificity <- st
  
  columns <- colnames(CP.sign)[! colnames(CP.sign) %in% c("Accession","Data")]
  ANOVAres <- ANOVAres[,c("Accession","Data", "Subtype.specificity",columns)]
  
  if (st =="SCLC-A"){
    ANOVAres <- rbind(ANOVAres[1,], ANOVAres)
    ANOVAres[1,] <- c("P50553", "CP", "SCLC-A", rep(NA, length(columns)))
  }
  
  if (st =="SCLC-P"){
    ANOVAres <- rbind(ANOVAres[1,], ANOVAres)
    ANOVAres[1,] <- c("Q8NE09", "CP", "SCLC-P", rep(NA, length(columns)))
  }
  
  if (st =="SCLC-Y"){
    ANOVAres <- rbind(ANOVAres[c(1:2),], ANOVAres)
    ANOVAres[1,] <- c("O95158", "CP", "SCLC-Y", rep(NA, length(columns)))
    ANOVAres[2,] <- c("Q58EX7", "CP", "SCLC-Y", rep(NA, length(columns)))
  }
  
  ANOVAres$Gene <- ""
  for (K in 1:nrow(ANOVAres)){
    ANOVAres$Gene[K] <- Protein.to.gene[Protein.to.gene$Protein == ANOVAres$Accession[K],"Gene"]
  }
  
  ANOVAres <- merge(ANOVAres, 
                    Protein.Annot[,c("Accession", "Secreted", "Surface", "Plasma.detect",
                                                                     "Blood.secr", "Druggable")], 
                    by="Accession")
  
  return(ANOVAres)
})


```



# Overrepresentation analysis with subtype-specific proteins

ClusterProfiler vs 4.4.4 was needed to fix error with KEGG DB

```{r eval=F}

ORA.SubtypeSpecific <- list()

i=1
for (i in 1:length(Subtype.specific)){
  proteins <- unique(Subtype.specific[[i]]$Accession)
  entrez.ids <- na.omit(UniProt.to.Entrez[UniProt.to.Entrez$UniProt %in%proteins,])
  entrez.ids <- entrez.ids[!duplicated(entrez.ids$UniProt),"Entrez"]
  
  ORA.SubtypeSpecific[[i]] <- list(GOBP = enrichGO(proteins,
                                                   ont="BP", 
                                                   OrgDb = org.Hs.eg.db, keyType ="UNIPROT", 
                                                   pvalueCutoff = 1, qvalueCutoff = 1),
                                   GOCC = enrichGO(proteins,
                                                   ont="CC", 
                                                   OrgDb = org.Hs.eg.db, keyType ="UNIPROT", 
                                                   pvalueCutoff = 1, qvalueCutoff = 1),
                                   GOMF = enrichGO(proteins,
                                                   ont="MF", 
                                                   OrgDb = org.Hs.eg.db, keyType ="UNIPROT", 
                                                   pvalueCutoff = 1, qvalueCutoff = 1),
                                   KEGG = enrichKEGG(gene = proteins,
                                                     organism = "hsa",
                                                     keyType ="uniprot",
                                                     pvalueCutoff = 1,
                                                     qvalueCutoff = 1),
                                   Reactome = enrichPathway(gene = entrez.ids,
                                                            organism     = "human",
                                                            pvalueCutoff = 1,
                                                            qvalueCutoff = 1))
}

save(ORA.SubtypeSpecific, file="RData/ORA_SubtypeSpecific_noSPfilter.RData")


```


# Export results


```{r }
load("RData/ORA_SubtypeSpecific_noSPfilter.RData")


ORA.SubtypeSpecific.summary <- ORA.SubtypeSpecific

subtypes <- c("SCLC-A", "SCLC-N", "SCLC-P", "SCLC-Y")
ST <- 1
for (ST in 1:length(ORA.SubtypeSpecific)){
  
  ORA.res <- ORA.SubtypeSpecific[[ST]]
  
  
  for (i in 1:length(ORA.res)){
    sheet.sub <- ORA.res[[i]]@result
    sheet.sub <- subset(sheet.sub, sheet.sub$pvalue < 0.05)
    sheet.sub$Database <- names(ORA.res)[i]
    if (i ==1){
      ORA.res.sum <- sheet.sub
    } else {
      ORA.res.sum <- rbind(ORA.res.sum,sheet.sub)
    }
  }
  
  for (j in 1:nrow(ORA.res.sum)){
    accessions <- unlist(lapply(ORA.res.sum$geneID[j], function(x){strsplit(x, split="/", fixed=T)}))
    if (accessions[1] %in% UniProt.to.Entrez$Entrez){
      new.names <-unlist(lapply(accessions, function(x){ 
        na.omit(UniProt.to.Entrez[UniProt.to.Entrez$Entrez==x,"UniProt"])[1] }))
    } else {
      new.names <- accessions
    }
    DE.tab.sub <- Subtype.specific[[ST]][Subtype.specific[[ST]]$Accession %in% new.names,]
    relevant.columns <- colnames(DE.tab.sub)[grepl("Log2FC(", colnames(DE.tab.sub), fixed=T)]
    relevant.columns <- relevant.columns[grepl(subtypes[ST], relevant.columns)]
    DE.tab.sub <- DE.tab.sub[c("Accession","Data", relevant.columns)]
    reverse.FC <- colnames(DE.tab.sub)[grepl(paste0("-",subtypes[ST]), colnames(DE.tab.sub), fixed=T)]
    
    if (length(reverse.FC)!=0){
      for (i in 1:length(reverse.FC)){
        DE.tab.sub[,reverse.FC[i]] <- -1* as.numeric(DE.tab.sub[,reverse.FC[i]])
      }
    }
    
    
    
    dupl.SP <- DE.tab.sub[duplicated(DE.tab.sub$Accession),"Accession"]
    directions <- new.names
    for (N in 1:length(new.names)){
      if (!new.names[N] %in% DE.tab.sub$Accession){ 
        directions[N] <- "ERROR"
        next
      }
      if (new.names[N] %in% dupl.SP){
        dir1 <- ifelse(mean(as.numeric(DE.tab.sub[DE.tab.sub$Accession == new.names[N] & DE.tab.sub$Data =="CP",
                                       grep("Log2FC(", colnames(DE.tab.sub),fixed=T)])) > 0, "UP","DOWN")
        dir2 <- ifelse(mean(as.numeric(DE.tab.sub[DE.tab.sub$Accession == new.names[N] & DE.tab.sub$Data =="CP",
                                  grep("Log2FC(", colnames(DE.tab.sub),fixed=T)])) > 0, "UP","DOWN")
        
        directions[N] <- paste0("cp",dir1, ", cm",dir2)
      } else {
        if (new.names[N] =="P50553" | new.names[N] =="Q8NE09"){
          directions[N] <- "UP"
        } else if (new.names[N] =="O95158" | new.names[N] =="Q58EX7") {
          directions[N] <- "DOWN"
        } else {
          directions[N] <- ifelse(mean(as.numeric(DE.tab.sub[DE.tab.sub$Accession == new.names[N],
                                       grep("Log2FC(", colnames(DE.tab.sub),fixed=T)])) > 0, "UP","DOWN")
        }
      }
    }
    
    gene.names <- paste(unlist(lapply(new.names, function(x){ 
      Protein.to.gene[Protein.to.gene$Protein ==x,"Gene"] })),collapse="/")
    ORA.res.sum$GeneNames[j] <- gene.names
    ORA.res.sum$Direction[j] <-  paste(directions,collapse="/")
  }
  
  ORA.res.sum <- ORA.res.sum[,c("Database", "ID", "Description", "GeneRatio", "BgRatio", "pvalue", "p.adjust", "qvalue", "geneID", "GeneNames", "Direction", "Count")]
  
  ORA.res.sum <- rbind(ORA.res.sum[ORA.res.sum$Database=="KEGG",], ORA.res.sum[ORA.res.sum$Database=="GOBP",],
                       ORA.res.sum[ORA.res.sum$Database=="GOCC",], ORA.res.sum[ORA.res.sum$Database=="GOMF",],
                       ORA.res.sum[ORA.res.sum$Database=="Reactome",])
  
  ORA.SubtypeSpecific.summary[[ST]] <- ORA.res.sum
  
}


```


```{r }
column.order <- c("Accession","Gene", "Data", "Subtype.specificity",
                  "Secreted","Surface", "Plasma.detect","Blood.secr", "Druggable", 
                  "Fvalues" ,"p.v Subtype" ,"p.adj Subtype" ,
                  "tukey(SCLC-N-SCLC-A)","tukey(SCLC-P-SCLC-A)","tukey(SCLC-Y-SCLC-A)" ,
                  "tukey(SCLC-P-SCLC-N)" , "tukey(SCLC-Y-SCLC-N)" ,"tukey(SCLC-Y-SCLC-P)",
                  "Log2FC(SCLC-N-SCLC-A)" ,"Log2FC(SCLC-P-SCLC-A)","Log2FC(SCLC-Y-SCLC-A)",
                  "Log2FC(SCLC-P-SCLC-N)" ,"Log2FC(SCLC-Y-SCLC-N)","Log2FC(SCLC-Y-SCLC-P)",
                  "Log2FC.95%.CI(SCLC-N-SCLC-A)","Log2FC.95%.CI(SCLC-P-SCLC-A)","Log2FC.95%.CI(SCLC-Y-SCLC-A)",
                  "Log2FC.95%.CI(SCLC-P-SCLC-N)","Log2FC.95%.CI(SCLC-Y-SCLC-N)","Log2FC.95%.CI(SCLC-Y-SCLC-P)")

Subtype.specific.common <- rbind(Subtype.specific[[1]][,column.order], 
                                 Subtype.specific[[2]][,column.order], 
                                 Subtype.specific[[3]][,column.order], 
                                 Subtype.specific[[4]][,column.order])
```


```{r eval=F}


wb <- createWorkbook(
  title = NULL,
)
sheetnames <- c("Subtype_specific_proteins","ORA_results_SCLCA","ORA_results_SCLCN", "ORA_results_SCLCP", "ORA_results_SCLCY")
sheets <- list(Subtype.specific.common, ORA.SubtypeSpecific.summary[[1]], ORA.SubtypeSpecific.summary[[2]], 
               ORA.SubtypeSpecific.summary[[3]], ORA.SubtypeSpecific.summary[[4]])

for (i in 1:length(sheets)) {
  addWorksheet(wb, sheetnames[i])
  writeData(
    wb = wb,
    sheet = sheetnames[i],
    x = sheets[[i]])
}
saveWorkbook(wb, paste0("Files/Supplementary_SubtypeSpecific_ORA_noSPfilter.xlsx"), overwrite = TRUE)




```


```{r }

Subtype.specific.summary <- unique(Subtype.specific.common[,c("Gene", "Secreted","Plasma.detect", "Blood.secr", "Druggable", "Surface")])

summary(as.factor(Subtype.specific.summary$Secreted))
summary(as.factor(Subtype.specific.summary$Plasma.detect))
summary(as.factor(Subtype.specific.summary$Blood.secr))
summary(as.factor(Subtype.specific.summary$Druggable))
summary(as.factor(Subtype.specific.summary$Surface))


```



# Export data for figures


```{r }
Subtype.specific.common.CP <- Subtype.specific.common[Subtype.specific.common$Data=="CP",] 
```


```{r , fig.width=12, fig.height=5}

set.seed(12345)
ht = Heatmap(as.matrix(t(scale(t(CP.expr[Subtype.specific.common.CP$Accession,])))),
                     name="Z-score",
             col=colorRamp2(c(-2, 0,2), c("blue","white","red")),
                     cluster_rows = T, #top_annotation = column.ha, 
             #column_labels =  Annot.Cluster$Sample,
             column_split = Annot$Subtype,  
             cluster_columns = T,
             cluster_row_slices = F,
             cluster_column_slices = F,
             #clustering_distance_columns = "pearson",
             clustering_method_columns = "complete",
             clustering_method_rows = "complete",
             #clustering_distance_rows = "pearson",
             #row_km  = 4,
             show_row_dend = F,
             show_row_names = F, 
             #row_title = NULL,
             column_gap = unit(0.1, "cm"),
             #row_title_gp = gpar(fontsize = 10),
             column_names_gp = gpar(fontsize = 12),
             #row_split = Subtype.specific.common.CP$Subtype.specificity, 
             gap = unit(0.1, "cm"),
             show_heatmap_legend = T,
             show_column_names =F,
             #height = unit(0.05, "cm"),
             #heatmap_height = unit(20, "cm"),
             heatmap_width = unit(12, "cm"))
draw(ht, annotation_legend_side="bottom",
             heatmap_legend_side="left")
```

```{r }
pdf(file="Figures/Graphical_abstract_heatmap.pdf",width = 12, height = 8)
draw(ht, annotation_legend_side="bottom",
             heatmap_legend_side="left")
dev.off()
```

```{r }

cnetplots <- list()

for (i in 1:length(ORA.SubtypeSpecific)){
  ORA.sum <- ORA.SubtypeSpecific[[i]]$KEGG
  ORA.sum@result <- ORA.sum@result[ORA.sum@result$pvalue < 0.05,]
  for (j in 1:nrow(ORA.sum@result)){
    proteins <- strsplit(ORA.sum@result$geneID[j], split="/", fixed=T)[[1]]
    genes <- Protein.to.gene[proteins,2]
    ORA.sum@result$geneID[j] <- paste(genes, collapse="/")
  }
  cnetplots[[i]] <- cnetplot(ORA.sum, showCategory = 15, circular=F)
}


```


```{r , fig.width=15, fig.height=15}

top_row <- plot_grid(cnetplots[[1]], cnetplots[[2]], cnetplots[[3]],
                     ncol = 3,
                     labels = c('A','N',"P"),
                     label_fontfamily = '',
                     label_fontface = 'bold',
                     label_size = 16,
                     align = 'h',
                     rel_widths = c(1,1,1))

bottom_row <- plot_grid(cnetplots[[4]],
                        ncol = 1,
                        labels = c('Y'),
                        label_fontfamily = '',
                        label_fontface = 'bold',
                        label_size = 16,
                        align = 'h',
                        rel_widths = c(1))

plot_grid(top_row, bottom_row, ncol = 1,
          rel_heights = c(0.75,1))


```



```{r }
save(Subtype.specific, ORA.SubtypeSpecific, Protein.to.gene, file= "RData/Fig_CNET_SubtypeSpecific_noSPfilter.RData")
```



