---
title: "Figure 3 and S4"
author: Beata Szeitz
output:
  html_notebook:
    toc: yes
---

```{r }
# R vs.4.2.0
source("Load_packages.R")
source("Utility_functions.R")
source("Color_list.R")
```
 

```{r}
loaded <- load("RData/CP_CM_PCAs_PVCAs.RData")
loaded
```

```{r }
CP.expr.imp.sd.scaled <- t(scale(t(CP.expr.imp.sd)))
CM.expr.imp.sd.scaled <- t(scale(t(CM.expr.imp.sd)))

```

# PVCA

```{r PVCAs, fig.width = 8, fig.height = 4}
annot.columns <- c("Subtype", 
                   "Culture type")
annot.pvca <- Annot[,annot.columns]
colnames(annot.pvca) <- c("Subtype", "Culture.type")

PVCA.CP <- plot_PVCA(as.data.frame(CP.expr.imp.sd), Annot, "Sample", 
          annot.columns, pct.threshold = 0.6, color="blue", 
          "", F)
PVCA.CP$Data <- "CP"
PVCA.CM <- plot_PVCA(as.data.frame(CM.expr.imp.sd), Annot, "Sample", 
          annot.columns, pct.threshold = 0.6, color="blue", 
          "", F)
PVCA.CM$Data <- "CM"

PVCA.CP.CM <- rbind(PVCA.CP, PVCA.CM)
PVCA.CP.CM$Data <- factor(PVCA.CP.CM$Data, levels = c("CP","CM"))

```

```{r , fig.width = 4, fig.height = 4}
ggplot(PVCA.CP.CM, aes(x=label, y=dat,fill=Data)) + ggtitle("SD > 1.25") + 
  geom_bar(stat="identity", position=position_dodge(), color="black")+
  #geom_text(aes(label=round(prop,3), y=prop+0.04), size=4)+ 
  scale_x_discrete(limits=PVCA.CP$label)+ scale_fill_manual(values=c("#eec892","lightblue"))+
  scale_y_continuous(limits = c(0,0.65))+labs(x= "Effects", y= "Weighted avr. proportion var.")+ 
  theme_classic()+theme(legend.position="bottom")#+ theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5))

ggsave(file="Figures/PVCA_CP_CM_SDfilt.pdf")

```

# PCA


```{r }
#Annot$To.label <- ifelse(Annot$Sample %in% c("H1882","H1048","H1688","DMS53"), Annot$Sample, "")
culture.type <- Annot$`Culture type`
CP.PCA <- ggbiplot(prcomp(t(na.omit(CP.expr.imp.sd.scaled))), 
                   choices= c(1,2),
                   var.axes=FALSE, 
                   #labels=Annot$To.label,
                   groups=Annot$Subtype,
                   labels.size = 3,
                   ellipse=T,
                   ellipse.prob = 0.95,
                   circle=F)  + theme_classic() + 
  geom_abline(intercept = 1.2, slope = -4, color="black", 
              linetype="dashed", size=1.5) +
  annotate("text", x=0.2, y=2.1, label= "Susp",fontface =2, color="black")+
  annotate("text", x=-0.8, y=2.1, label= "Adh",fontface =2, color="black")+ggtitle("CP (SD > 1.25)")+ 
  #annotate("text", x=-0.45, y=-0.55, label= "H1048",fontface =2, color="red")+
  annotate("text", x=-0.85, y=-1.0, label= "H1882",fontface =2, color="red")+
  annotate("text", x=-0.15, y=-2.1, label= "H1688",fontface =2, color="red")+
  annotate("text", x=-0.1, y=-2.35, label= "DMS53",fontface =2, color="red")+
  geom_point(aes(shape=culture.type, color=Annot$Subtype), size=3)+scale_shape_manual(values=c(16, 8, 15))+
  scale_color_manual(values=c("#0000FE","#21FE06","gold","#FB02FE")) + xlab("PC1 (17.4% explained var.)")+
  ylab("PC2 (9.7% explained var.)")

CP.PCA
CM.PCA <- ggbiplot(prcomp(t(na.omit(CM.expr.imp.sd.scaled))), 
                        choices= c(1,2),
                        var.axes=FALSE, 
                        #labels=Annot$Name,
                        groups=Annot$Subtype,
                        labels.size = 3,
                        ellipse=F,
                        ellipse.prob = 0.95,
                        circle=F)  + theme_classic() + 
  geom_abline(intercept = -0.5, slope = 2.5, color="black", 
              linetype="dashed", size=1.5) +
  annotate("text",  x=-1, y=-2, label= "Susp",fontface =2, color="black")+
  annotate("text", x=-0.3, y=-2, label= "Adh",fontface =2,  color="black")+ggtitle("CM (SD > 1.25)")+ 
  geom_point(aes(shape=culture.type, color=Annot$Subtype), size=3)+scale_shape_manual(values=c(16, 8, 15))+
  scale_color_manual(values=c("#0000FE","#21FE06","gold","#FB02FE"))+ xlab("PC1 (18.5% explained var.)")+
  ylab("PC2 (13.9% explained var.)")

CM.PCA
```

```{r , fig.width=12, fig.height=5}
ggarrange(CP.PCA, CM.PCA, 
          ncol=2, nrow=1)

ggsave(file="Figures/PCA_CP_CM_SDfilt.pdf")


```

# Consensus clustering


```{r }
loaded <- load("RData/Fig_consClust.RData")
loaded
```




```{r , }
Annot.Cluster[,"K4"] <- cluster.res[[4]][["consensusClass"]]
Annot.Cluster[,"K5"] <- cluster.res[[5]][["consensusClass"]]

par(mfrow=c(1,2))
dis = Dist(t(as.matrix(CP.expr.imp.sd)), method = "pearson")
sil = silhouette (cluster.res[[4]][["consensusClass"]], dis, nmax.lab = 30, max.strlen = 10)
plot(sil, main="K=4")
sil = silhouette (cluster.res[[5]][["consensusClass"]], dis, nmax.lab = 30, max.strlen = 10)
plot(sil, main="K=5")

```

```{r ,eval=F}
pdf(file="Figures/Silhouette_plots.pdf", width = 13, height = 8)
par(mfrow=c(1,2))
dis = amap::Dist(t(as.matrix(CP.expr.imp.sd)), method = "pearson")
sil = silhouette (cluster.res[[4]][["consensusClass"]], dis, nmax.lab = 30, max.strlen = 10)
plot(sil, main="K=4")
sil = silhouette (cluster.res[[5]][["consensusClass"]], dis, nmax.lab = 30, max.strlen = 10)
plot(sil, main="K=5")
dev.off()
```


```{r , fig.width=12, fig.height=12}
column.ha = HeatmapAnnotation(df =Annot.Cluster[,c("Subtype", "ASCL1 qPCR", "NEUROD1 qPCR", "POU2F3 qPCR", "YAP1 qPCR","Culture type","Cell line origin","Chemo")],
                              which="col",
                              col=colorlist,
                              annotation_name_side = "right",
                              gp = gpar(col = "grey"),
                              "NE score" = anno_barplot(Annot.Cluster$NEscore,
                                                        gp = gpar(fill =  c("#76069a")),
                                                        height = unit(1.5, "cm"),
                                                        axis_param = list(
                                                          side = "left",
                                                          at = c(-2.25,0,1.5), 
                                                          labels = c("-2.25","0", "+1.5") )),
                              "EMT score" = anno_barplot(Annot.Cluster$EMTscore,
                                                            gp = gpar(fill =  c("#005757")),
                                                            height = unit(1.5, "cm"),
                                                            axis_param = list(
                                                              side = "left",
                                                              at = c(-1.9,0,1.6), 
                                                              labels = c("-1.9","0", "+1.6") )),
                              gap = unit(c(2,1,1,1,2,1,1,1.5,2), 'mm'),
                              show_legend = TRUE,
                              show_annotation_name = TRUE)
set.seed(12345)
ht = Heatmap(as.matrix(CP.expr.imp.sd.scaled),
                     name="Z-score",
             col=colorRamp2(c(-2, 0,2), c("blue","white","red")),
                     cluster_rows = T, top_annotation = column.ha, 
             column_labels =  Annot.Cluster$Sample,
             column_split = Annot.Cluster$Cluster,  
             cluster_columns = T,
             #clustering_distance_columns = "pearson",
             clustering_method_columns = "complete",
             clustering_method_rows = "complete",
             #clustering_distance_rows = "pearson",
             #row_km  = 4,
             show_row_dend = F,
             show_row_names = F, 
             #row_title = NULL,
             column_gap = unit(0.1, "cm"),
             #row_title_gp = gpar(fontsize = 10),
             column_names_gp = gpar(fontsize = 12),
             #row_split = rowsplits, 
             gap = unit(0.1, "cm"),
             show_heatmap_legend = T,
             show_column_names = T,
             #height = unit(0.05, "cm"),
             #heatmap_height = unit(20, "cm"),
             heatmap_width = unit(10, "cm"))
ht = draw(ht, annotation_legend_side="bottom",
             heatmap_legend_side="left")
```


```{r ,eval=F}
pdf(file="Figures/Consclust_heatmap_420.pdf",width = 12, height = 12)
ht = draw(ht, annotation_legend_side="bottom",
             heatmap_legend_side="left")
dev.off()

```

