---
title: "Figure 3 and 4ab"
author: Beata Szeitz
output:
  html_notebook:
    toc: yes
---

```{r Load packages}
source("Install_load_packages.R")
source("Utility_functions.R")
source("Color_list.R")
```
 

```{r}
loaded <- load("RData/Fig_CNET_SubtypeSpecific.RData")
loaded
```

```{r fig.width=15, fig.height=15}

cnetplots <- list()

for (i in 1:length(ORA.SubtypeSpecific)){
  ORA.sum <- ORA.SubtypeSpecific[[i]]$KEGG
  ORA.sum@result <- ORA.sum@result[ORA.sum@result$pvalue < 0.05,]
  for (j in 1:nrow(ORA.sum@result)){
    proteins <- strsplit(ORA.sum@result$geneID[j], split="/", fixed=T)[[1]]
    genes <- Protein.to.gene[proteins,2]
    ORA.sum@result$geneID[j] <- paste(genes, collapse="/")
  }
  cnetplots[[i]] <- cnetplot(ORA.sum, showCategory = 15, circular=F)
}


```




```{r , fig.width=20, fig.height=20}

top_row <- plot_grid(cnetplots[[1]], cnetplots[[2]], cnetplots[[3]],
                     ncol = 3,
                     labels = c('SCLC-A','SCLC-N',"SCLC-P"),
                     label_fontfamily = '',
                     label_fontface = 'bold',
                     label_size = 16,
                     align = 'h',
                     rel_widths = c(1,1,1))

bottom_row <- plot_grid(cnetplots[[4]],
                        ncol = 1,
                        labels = c('SCLC-Y'),
                        label_fontfamily = '',
                        label_fontface = 'bold',
                        label_size = 16,
                        align = 'h',
                        rel_widths = c(1))

plot_grid(top_row, bottom_row, ncol = 1,
          rel_heights = c(0.75,1))


ggsave("Figures/SubtypeSpecific_cnetplot.pdf", width = 20, height=20)
```




