---
title: "Figure S2"
author: Beata Szeitz
output:
  html_notebook:
    toc: yes
---

```{r }
source("Install_load_packages.R")
source("Utility_functions.R")
source("Color_list.R")
```
 
```{r Load files}
Annot <- read_in_with_rowname("Files/Annotation",F)
Scores <- read_in_with_rowname("Files/NE_EMT_scores",F)
Annot <- merge(Annot, Scores[,c("Sample", "NEscore", "EMTscore")], by="Sample")
row.names(Annot) <- Annot$Sample
CP.expr.imp <- read_in_with_rowname("Files/CP_expression_filtered_imputed",F)[,Annot$Sample]
CM.expr.imp <- read_in_with_rowname("Files/CM_expression_filtered_imputed",F)[,Annot$Sample]
CP.expr <- read_in_with_rowname("Files/CP_expression_full",F)[,Annot$Sample]
CM.expr <- read_in_with_rowname("Files/CM_expression_full",F)[,Annot$Sample]
Secreted.proteins <- read_in_with_rowname("Files/Tier1_and_2_secreted",F)[,1]
CM.expr.imp.secr <- CM.expr.imp[row.names(CM.expr.imp) %in% Secreted.proteins,]
prot.to.gene <- read_in_with_rowname("Files/Protein_to_Gene",F)
CP.expr.imp.genes <- prot.to.gene[prot.to.gene$Protein %in% row.names(CP.expr.imp),"Gene"]
```


```{r }
Markers <- as.data.frame(read_xlsx("Files/SCLC_markers_literature.xlsx"))
Markers <- Markers[Markers$Identified =="Yes",]
Markers <- Markers[Markers$Gene %in% CP.expr.imp.genes,]
duplicated.markers <- Markers[duplicated(Markers$Gene),"Gene"]
duplicated.markers <- Markers[Markers$Gene %in% duplicated.markers,]
duplicated.markers[order(duplicated.markers$Gene),]

Markers.list <- list("SCLC-A" = Markers[grep("in A", Markers$Literature),],
                     "SCLC-N" = Markers[grep("in N", Markers$Literature),],
                     "SCLC-P" = Markers[grep("in P", Markers$Literature),],
                     "SCLC-Y" = Markers[grep("in Y", Markers$Literature),])


column.ha = HeatmapAnnotation(df =Annot[,c("Subtype", "ASCL1 qPCR", "NEUROD1 qPCR", "POU2F3 qPCR", "YAP1 qPCR","Culture type","Cell line origin","Chemo")],
                              which="col",
                              col=colorlist,
                              annotation_name_side = "right",
                              gp = gpar(col = "grey"),
                              "NE score" = anno_barplot(Annot$NEscore,
                                                        gp = gpar(fill =  c("#76069a")),
                                                        height = unit(1.5, "cm"),
                                                        axis_param = list(
                                                          side = "left",
                                                          at = c(-2.25,0,1.5), 
                                                          labels = c("-2.25","0", "+1.5") )),
                              "EMT score" = anno_barplot(Annot$EMTscore,
                                                            gp = gpar(fill =  c("#005757")),
                                                            height = unit(1.5, "cm"),
                                                            axis_param = list(
                                                              side = "left",
                                                              at = c(-1.9,0,1.6), 
                                                              labels = c("-1.9","0", "+1.6") )),
                              gap = unit(c(2,1,1,1,2,1,1,1.5,2), 'mm'),
                              show_legend = TRUE,
                              show_annotation_name = TRUE)

```


```{r , fig.width=15, fig.height=15}

lapply(seq(1:4), function(x){
 proteins.and.genes <- merge(Markers.list[[x]], prot.to.gene, by="Gene")
  draw(Heatmap(as.matrix(t(scale(t(CP.expr.imp[proteins.and.genes$Protein,])))),
                     name="Z-score",
             col=colorRamp2(c(-2, 0,2), c("blue","white","red")),
                     cluster_rows = T, top_annotation = column.ha, 
             #column_labels =  Annot.Cluster$Sample,
             column_split = Annot$Subtype,  
             cluster_columns = T,
             cluster_column_slices = F,
             cluster_row_slices = F,
             #clustering_distance_columns = "pearson",
             clustering_method_columns = "complete",
             clustering_method_rows = "complete",
             #clustering_distance_rows = "pearson",
             #row_km  = 4,
             show_row_dend = T,
             show_row_names = T, 
             #row_title = NULL,
             column_gap = unit(0.1, "cm"),
             row_title_gp = gpar(fontsize = 10),
             row_names_gp = gpar(fontsize = 10),
             column_names_gp = gpar(fontsize = 10),
             row_split = proteins.and.genes$Literature, 
             gap = unit(0.1, "cm"),
             show_heatmap_legend = T,
             row_labels = proteins.and.genes$Gene,
             show_column_names = T,
             height = unit(nrow(proteins.and.genes)*0.45, "cm"),
             #heatmap_height = unit(20, "cm"),
             heatmap_width = unit(12, "cm")), 
       annotation_legend_side="bottom",
             heatmap_legend_side="left")
  return()
})


```


```{r }
Markers <- as.data.frame(read_xlsx("Files/SCLC_markers_literature.xlsx"))
Markers <- Markers[Markers$Identified =="Yes",]
Markers <- Markers[!is.na(Markers$Gene),]

Gene.direction.summary <- data.frame(Gene = unique(Markers$Gene),
                                     Direction = NA)

for (i in 1:nrow(Gene.direction.summary)){
  Gene.direction.summary$Direction[i] <- paste(Markers[Markers$Gene == Gene.direction.summary$Gene[i],"Literature"], collapse=", ")
}

Gene.direction.summary <- merge(Gene.direction.summary, prot.to.gene, by="Gene")

```





```{r }

Markers.melt <- CP.expr[Gene.direction.summary$Protein,]
Markers.melt$Gene <- Gene.direction.summary$Gene
Markers.melt$Protein <- Gene.direction.summary$Protein

Markers.melt <-   reshape2::melt(Markers.melt)

colnames(Markers.melt)[3:4] <- c("Sample", "LFQ.value")

Markers.melt <- merge(Markers.melt, Annot[,c("Sample","Subtype")], by="Sample")
Markers.melt$Subtype <- unlist(lapply(Markers.melt$Subtype, function(x){strsplit(x, split="-")[[1]][2]}))
Markers.melt <- merge(Markers.melt, Gene.direction.summary[,c("Gene","Direction")])


gene.order <- c(Gene.direction.summary[Gene.direction.summary$Direction =="UP in A","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="DOWN in A","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="UP in N","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="DOWN in N","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="UP in P","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="DOWN in P","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="UP in Y","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="DOWN in Y","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="UP in A, DOWN in N, UP in P","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="UP in A, DOWN in P","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="UP in A, UP in N, DOWN in P, DOWN in Y","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="UP in A, UP in N","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="UP in A, DOWN in N, DOWN in P","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="DOWN in A, UP in N, UP in P, DOWN in Y","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="UP in N, UP in P, UP in Y","Gene"],
                Gene.direction.summary[Gene.direction.summary$Direction =="UP in P, UP in Y","Gene"])

row.names(Gene.direction.summary) <- Gene.direction.summary$Gene

Gene.direction.summary <- Gene.direction.summary[gene.order,]

Markers.melt$Gene <- factor(Markers.melt$Gene, levels = gene.order)

unique(Gene.direction.summary$Direction)

Gene.direction.summary$Direction <- ifelse(Gene.direction.summary$Direction == "UP in A, DOWN in N, UP in P", "UP in A&P, DOWN in N", Gene.direction.summary$Direction)
Gene.direction.summary$Direction <- ifelse(Gene.direction.summary$Direction == "UP in A, UP in N, DOWN in P, DOWN in Y", "UP in A&N, DOWN in P&Y",
                                 Gene.direction.summary$Direction)
Gene.direction.summary$Direction <- ifelse(Gene.direction.summary$Direction == "UP in A, UP in N", "UP in A&N",
                                 Gene.direction.summary$Direction)
Gene.direction.summary$Direction <- ifelse(Gene.direction.summary$Direction == "UP in A, DOWN in N, DOWN in P", "UP in A, DOWN in N&P",
                                 Gene.direction.summary$Direction)
Gene.direction.summary$Direction <- ifelse(Gene.direction.summary$Direction == "DOWN in A, UP in N, UP in P, DOWN in Y", "UP in N&P, DOWN in A&Y",
                                 Gene.direction.summary$Direction)
Gene.direction.summary$Direction <- ifelse(Gene.direction.summary$Direction == "UP in N, UP in P, UP in Y", "UP in N&P&Y",
                                 Gene.direction.summary$Direction)
Gene.direction.summary$Direction <- ifelse(Gene.direction.summary$Direction == "UP in P, UP in Y", "UP in P&Y",
                                 Gene.direction.summary$Direction)


unique(Gene.direction.summary$Direction)


```





```{r , fig.width=15, fig.height=40}
my_comparisons <- list( c("N", "A"),c("P", "A"), c("N", "P"), c("Y", "A"), c("Y", "N"), c("Y", "P") )
names.my_comparisons <- c("NA", "PA", "NP", "YA", "YN", "YP")

glist <- list()

for (i in 1:length(Gene.direction.summary$Gene)){
  
  direct <- Gene.direction.summary$Direction[i]
  if (direct %in% c("UP in A","DOWN in A")){
    comps <- my_comparisons[grep("A", names.my_comparisons)]
  } else if (direct %in% c("UP in N")){
    comps <- my_comparisons[grep("N", names.my_comparisons)]
  } else if (direct %in% c("UP in P","DOWN in P")){
    comps <- my_comparisons[grep("P", names.my_comparisons)]
  } else if (direct %in% c("UP in Y")){
    comps <- my_comparisons[grep("Y", names.my_comparisons)]
  } else {
    comps <- my_comparisons
  } 
  

  g <- ggplot(Markers.melt[Markers.melt$Gene ==Gene.direction.summary$Gene[i],], 
              aes(x=Subtype, y=LFQ.value, fill=Subtype))+ theme_bw()+# +geom_violin()  
    scale_color_manual(values=c("#0000FE", "#21FE06","#FEFE0A", "#FB02FE"))+ 
    scale_fill_manual(values=c("#0000FE", "#21FE06","#FEFE0A", "#FB02FE"))+ 
    geom_boxplot() + ylab("LFQ value")+xlab("")+
    geom_point()+ ggtitle(Gene.direction.summary$Gene[i], 
                          subtitle = paste0("Exp.Dir.: ", Gene.direction.summary$Direction[i]))+
  theme(legend.position="none")+ 
    theme(plot.title = element_text(size = 10),
          plot.subtitle = element_text(size = 8))+
    stat_compare_means(label = "p.signif", method = "anova")+
    stat_compare_means(comparisons = comps,label = "p.signif", method = "t.test")
  glist[[i]] <- g
}

g <- grid.arrange(grobs=glist, ncol=6)

```





```{r }
best.markers <- c("CHGA", "DLL3", "SOX2", "NOTCH1", 
                  "ANTXR1", 
                  "ASCL2", "AVIL", "CHAT", 
                  "IGF1R", "TRPM5", 
                  "ITGA1","ITGA3", "ITGA5", "ITGAV", "ITGB1",
                   "CDH1", "IGFBP5","INSM1")
```




```{r , fig.width=15, fig.height=10}
glist <- list()

for (i in 1:length(best.markers)){
  gene <- best.markers[i]
  direct <- Gene.direction.summary[Gene.direction.summary$Gene==gene,"Direction"]
  if (direct %in% c("UP in A","DOWN in A")){
    comps <- my_comparisons[grep("A", names.my_comparisons)]
  } else if (direct %in% c("UP in N")){
    comps <- my_comparisons[grep("N", names.my_comparisons)]
  } else if (direct %in% c("UP in P","DOWN in P")){
    comps <- my_comparisons[grep("P", names.my_comparisons)]
  } else if (direct %in% c("UP in Y")){
    comps <- my_comparisons[grep("Y", names.my_comparisons)]
  } else {
    comps <- my_comparisons
  } 
  

  g <- ggplot(Markers.melt[Markers.melt$Gene ==gene,], 
              aes(x=Subtype, y=LFQ.value, fill=Subtype))+ theme_bw()+# +geom_violin()  
    scale_color_manual(values=c("#0000FE", "#21FE06","#FEFE0A", "#FB02FE"))+ 
    scale_fill_manual(values=c("#0000FE", "#21FE06","#FEFE0A", "#FB02FE"))+ 
    geom_boxplot() + ylab("LFQ value")+xlab("")+
    geom_point()+ ggtitle(gene, 
                          subtitle = paste0(direct))+
  theme(legend.position="none")+ 
    theme(plot.title = element_text(size = 12),
          plot.subtitle = element_text(size = 10))+
    #stat_compare_means(label = "p.signif", method = "anova")+
    stat_compare_means(comparisons = comps,label = "p.signif", method = "t.test",na.rm = T)
  glist[[i]] <- g
}

g <- grid.arrange(grobs=glist, ncol=6)

#g
ggsave(file="Figures/Subtype_markers_literature.pdf", g, height = 10, width = 15)
ggsave(file="Figures/Subtype_markers_literature.svg", g, height = 10, width = 15)

```
