---
title: "Figure 1"
author: Beata Szeitz
output:
  html_notebook:
    toc: yes
---

```{r }
source("Install_load_packages.R")
source("Utility_functions.R")
source("Color_list.R")
```
 

```{r}
loaded <- load("RData/Fig_DEA_culture.RData")
loaded
```

```{r }
highlighted.pathways <- c("Protein processing in endoplasmic reticulum", "ECM-receptor interaction", 
              "collagen binding", "laminin binding", "extracellular matrix binding")
DB <- c("KEGG", "KEGG", "GOMF", "GOMF","GOMF")

all.proteins <- vector()

for (i in 1:length(highlighted.pathways)){
  all.proteins <- unique(c(all.proteins, strsplit(ORA.Susp.vs.Adh[[DB[i]]]@result[ORA.Susp.vs.Adh[[DB[i]]]@result$Description == highlighted.pathways[i], 
                                                                                  "geneID"], 
                                                  split="/", fixed=T)[[1]]))
}

```


```{r Create table for the figure}

CM.Culture.ANOVA.SPs.sign <- CM.Culture.ANOVA.SPs[CM.Culture.ANOVA.SPs$`p.adj Culture` < 0.05,]

CP.de <- CP.Culture.ANOVA[!row.names(CP.Culture.ANOVA)%in%CM.Culture.ANOVA.SPs.sign$Accession,c("Log2FC(Susp-Adh)", "tukey(Susp-Adh)", "p.adj Culture")]
colnames(CP.de) <-c("log2FoldChange", "p.value", "global.p.value") 
CP.de$Accession <- row.names(CP.Culture.ANOVA[!row.names(CP.Culture.ANOVA)%in%CM.Culture.ANOVA.SPs.sign$Accession,])
CP.de$Data <- "CP"

CM.de <-CM.Culture.ANOVA.SPs[,c("Log2FC(Susp-Adh)", "tukey(Susp-Adh)", "p.adj Culture")]
colnames(CM.de) <-c("log2FoldChange", "p.value", "global.p.value") 
CM.de$Accession <- row.names(CM.Culture.ANOVA.SPs)
CM.de$Data <- "CM"

de <- rbind(CP.de, CM.de)
de$diffexpressed <- ifelse(de$p.value < 0.05 & de$global.p.value < 0.05, "yes", "no")
de$delabel <- ifelse(de$diffexpressed =="yes", de$Accession, "")
for (i in 1:nrow(de)){
  if (de$delabel[i] %in% all.proteins){
    de$Category[i] <- "Highlighted"
  } else {
    de$Category[i] <- "Not Highlighted"
  }
}
de$Category <- ifelse(de$diffexpressed !="yes", "Not Significant", de$Category)

de$delabel <- ifelse(de$Category =="Highlighted", de$Accession, "")
de$Category <- ifelse(de$Category == "Highlighted" & de$log2FoldChange < 0, "Highlighted - DOWN in suspension", de$Category)
de$Category <- ifelse(de$Category == "Highlighted" & de$log2FoldChange > 0, "Highlighted - UP in suspension", de$Category)

de$Category <- ifelse(de$Category != "Highlighted - UP in suspension" & de$Category != "Highlighted - DOWN in suspension" & 
                        de$log2FoldChange > 0 & de$diffexpressed =="yes", 
                      "Not Highlighted - UP in suspension", de$Category)
de$Category <- ifelse(de$Category != "Highlighted - UP in suspension" & de$Category != "Highlighted - DOWN in suspension" &
                        de$log2FoldChange < 0 & de$diffexpressed =="yes", 
                      "Not Highlighted - DOWN in suspension", de$Category)

de$Color <- paste(de$Category, de$Data, sep="_")

de$Category <- factor(de$Category, levels = c("Not Significant", 
                                              "Not Highlighted - DOWN in suspension", 
                                              "Not Highlighted - UP in suspension",
                                              "Highlighted - DOWN in suspension", 
                                              "Highlighted - UP in suspension"))

de$Color <- ifelse(grepl("DOWN in suspension_CP",de$Color), "DOWN in suspension_CP",de$Color)
de$Color <- ifelse(grepl("UP in suspension_CP",de$Color), "UP in suspension_CP",de$Color)
de$Color <- ifelse(grepl("DOWN in suspension_CM",de$Color), "DOWN in suspension_CM",de$Color)
de$Color <- ifelse(grepl("UP in suspension_CM",de$Color), "UP in suspension_CM",de$Color)

de$Color <- factor(de$Color, levels = c("Not Significant_CP","Not Significant_CM", 
                                              "DOWN in suspension_CP","DOWN in suspension_CM", 
                                              "UP in suspension_CP", "UP in suspension_CM"))


for (i in 1:nrow(de)){
  if(de$delabel[i] !=""){
    de$delabel[i] <- Protein.to.gene[Protein.to.gene$Protein ==de$delabel[i],"Gene"]
  }
}
```



```{r , fig.width=12, fig.height=12}

ggplot(data=de, aes(x=log2FoldChange, y=-log10(global.p.value), col=Color, label=delabel)) + 
    geom_point() + 
    theme_classic()+
  geom_label_repel(max.overlaps = 1000, seed=1234, aes(label = delabel)) +  
  scale_color_manual(values=c("darkgrey","lightblue", "#089000","blue","#800080", "#ff0081"))+
  xlab("log2FC(suspension vs adherent cell lines)")+ylab("-log10(p-value)")+ ylim(0.0001,3.15)+ xlim(-5.2,5.2)+
  theme(legend.position="bottom",
        legend.title = element_text(size=16),legend.text = element_text(size=16),
        axis.text.x = element_text(size=18),
        axis.text.y = element_text(size=18),
        axis.title=element_text(size=18,face="bold"))

ggsave(file="Figures/DEA_Culture_volcano.pdf")

```






```{r}
loaded <- load("RData/NE_scores_heatmap.RData")
loaded
```





```{r , fig.width=15, fig.height=4}

draw(Heatmap(Avr.NE.values,
                     name="Avr. Z-score",
             col=colorRamp2(c(-2, 0, 2), c("blue","white", "red")),
                     cluster_rows = F, top_annotation = column.ha.NEscore, 
             column_split = Annot.NEscore$Subtype, 
             cluster_columns = T,
             show_row_names = T, 
             show_heatmap_legend = T, 
             cluster_column_slices = F,
             row_title_gp = gpar(fontsize = 12),
             row_names_gp = gpar(fontsize = 10),
             gap = unit(2, "mm"),
             heatmap_width = unit(15, "cm")),
             annotation_legend_side="right",
             heatmap_legend_side="right")

```



```{r }

pdf(file="Figures/NE_scores_heatmap.pdf",width = 15, height = 4)
draw(Heatmap(Avr.NE.values,
                     name="Avr. Z-score",
             col=colorRamp2(c(-2, 0, 2), c("blue","white", "red")),
                     cluster_rows = F, top_annotation = column.ha.NEscore, 
             column_split = Annot.NEscore$Subtype, 
             cluster_columns = T,
             show_row_names = T, 
             show_heatmap_legend = T, 
             cluster_column_slices = F,
             row_title_gp = gpar(fontsize = 12),
             row_names_gp = gpar(fontsize = 10),
             gap = unit(2, "mm"),
             heatmap_width = unit(15, "cm")),
             annotation_legend_side="right",
             heatmap_legend_side="right")
dev.off()

```


```{r}
loaded <- load("RData/EMT_scores_heatmap.RData")
loaded
```


```{r , fig.width=15, fig.height=4}

draw(Heatmap(Avr.EMT.values, 
                     name="Avr. Z-score",
             col=colorRamp2(c(-2, 0, 2), c("blue","white", "red")),
                     cluster_rows = F, top_annotation = column.ha.EMTscore, 
             column_split = Annot.EMTscore$Subtype, 
             cluster_columns = T,
             show_row_names = T, 
             show_heatmap_legend = T, 
             cluster_column_slices = F,
             row_title_gp = gpar(fontsize = 12),
             row_names_gp = gpar(fontsize = 10),
             gap = unit(2, "mm"),
             heatmap_width = unit(15, "cm")),
             annotation_legend_side="right",
             heatmap_legend_side="right")
```



```{r }

pdf(file="Figures/EMT_scores_heatmap.pdf",width = 15, height = 4)
draw(Heatmap(Avr.EMT.values, 
                     name="Avr. Z-score",
             col=colorRamp2(c(-2, 0, 2), c("blue","white", "red")),
                     cluster_rows = F, top_annotation = column.ha.EMTscore, 
             column_split = Annot.EMTscore$Subtype, 
             cluster_columns = T,
             show_row_names = T, 
             show_heatmap_legend = T, 
             cluster_column_slices = F,
             row_title_gp = gpar(fontsize = 12),
             row_names_gp = gpar(fontsize = 10),
             gap = unit(2, "mm"),
             heatmap_width = unit(15, "cm")),
             annotation_legend_side="right",
             heatmap_legend_side="right")
dev.off()
```





