---
title: "Figure S1"
author: Beata Szeitz
output:
  html_notebook:
    toc: yes
---

```{r Load packages}
source("Install_load_packages.R")
source("Utility_functions.R")
source("Color_list.R")
```
 

```{r}
loaded <- load("RData/Fig_QC_PCA_PVCA_HC.RData")
loaded
```



```{r Cleaned PCA plots before and after merging technical replicates, fig.width = 15, fig.height = 5}

CP.PCA.before <- ggbiplot(prcomp(t(na.omit(Fig_QC_PCA_PVCA_HC$CP$Expr.Med.withinBatch))),
         circle=F, scale = T, 
         groups = as.factor(Fig_QC_PCA_PVCA_HC$CP$Annot.Med.withinBatch[,"MSbatch"]),
         ellipse = T,
         var.axes	=F) + 
  ggtitle("CP\n  Colored by MS batch")+
  theme_bw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
CM.PCA.before <- ggbiplot(prcomp(t(na.omit(Fig_QC_PCA_PVCA_HC$CM$Expr.Med.withinBatch))),
         circle=F, scale = T, 
         groups = as.factor(Fig_QC_PCA_PVCA_HC$CM$Annot.Med.withinBatch[,"MSbatch"]),
         ellipse = T,
         var.axes	=F) + 
  ggtitle("CM\n  Colored by MS batch")+
  theme_bw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

ggarrange(CP.PCA.before, CM.PCA.before)

```



```{r Cleaned PCA plots after batch correction, fig.width = 15, fig.height = 5}

CP.PCA.after <- ggbiplot(prcomp(t(na.omit(Fig_QC_PCA_PVCA_HC$CP$Expr.Med.withinBatch.F.BatchCorr))),
         circle=F, scale = T, 
         groups = as.factor(Fig_QC_PCA_PVCA_HC$CP$Annot.Med.withinBatch[,"MSbatch"]),
         ellipse = T,
         var.axes	=F) + 
  ggtitle("CP\n  Colored by MS batch")+
  theme_bw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
CM.PCA.after <- ggbiplot(prcomp(t(na.omit(Fig_QC_PCA_PVCA_HC$CM$Expr.Med.withinBatch.F.BatchCorr))),
         circle=F, scale = T, 
         groups = as.factor(Fig_QC_PCA_PVCA_HC$CM$Annot.Med.withinBatch[,"MSbatch"]),
         ellipse = T,
         var.axes	=F) + 
  ggtitle("CM\n  Colored by MS batch")+
  theme_bw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

ggarrange(CP.PCA.after, CM.PCA.after)

```





```{r Show all cleaned PCA plots, fig.width = 15, fig.height = 4}
lim.down <- -2.8
lim.up <- 2.8
g <- ggarrange(CP.PCA.before +xlim(lim.down,lim.up) + ylim(lim.down,lim.up) + xlab("PC1 (16.2% explained var.)") + ylab("PC2 (14.1% explained var.)"), 
               CM.PCA.before+xlim(lim.down,lim.up) + ylim(lim.down,lim.up)+ xlab("PC1 (18.4% explained var.)") + ylab("PC2 (13.8% explained var.)"),
               CP.PCA.after+xlim(lim.down,lim.up) + ylim(lim.down,lim.up)+ xlab("PC1 (16.8% explained var.)") + ylab("PC2 (14.8% explained var.)"),
               CM.PCA.after+xlim(lim.down,lim.up) + ylim(lim.down,lim.up)+ xlab("PC1 (18.7% explained var.)") + ylab("PC2 (14.4% explained var.)"), 
               ncol=4)
g
ggsave(file="Figures/PCA_before_after_batch_correction.pdf", g)
```



```{r PVCA plots, fig.width = 18, fig.height = 5}
columns.to.include <- c("MSbatch", "Subtype", "Culture type")
g <- ggarrange(plot_PVCA(Fig_QC_PCA_PVCA_HC$CP$Expr.Med.withinBatch, Fig_QC_PCA_PVCA_HC$CP$Annot.Med.withinBatch, 
                    ID.column = "MainID", columns.to.include = columns.to.include, 
                    pct.threshold = 0.6, color="blue", title = "CP - before batch correction", figure = T),
          plot_PVCA(Fig_QC_PCA_PVCA_HC$CM$Expr.Med.withinBatch, Fig_QC_PCA_PVCA_HC$CM$Annot.Med.withinBatch, 
                    ID.column = "MainID", columns.to.include = columns.to.include, 
                    pct.threshold = 0.6, color="blue", title = "CM - before batch correction", figure = T),
          plot_PVCA(Fig_QC_PCA_PVCA_HC$CP$Expr.Med.withinBatch.F.BatchCorr, Fig_QC_PCA_PVCA_HC$CP$Annot.Med.withinBatch, 
                    ID.column = "MainID", columns.to.include = columns.to.include, 
                    pct.threshold = 0.6, color="blue", title = "CP - after batch correction", figure = T),
          plot_PVCA(Fig_QC_PCA_PVCA_HC$CM$Expr.Med.withinBatch.F.BatchCorr, Fig_QC_PCA_PVCA_HC$CM$Annot.Med.withinBatch, 
                    ID.column = "MainID", columns.to.include = columns.to.include, 
                    pct.threshold = 0.6, color="blue", title = "CM - after batch correction", figure = T),
          ncol=4)
g
ggsave(file="Figures/PVCA_before_after_batch_correction.pdf", g)
```


```{r Heatmaps after batch correction, fig.width=20, fig.height=8}
annot.columns <- c("Subtype", "ASCL1 qPCR", "NEUROD1 qPCR", "POU2F3 qPCR", "YAP1 qPCR", "Cell line origin",
                   "Culture type", "MSbatch")

draw(Heatmap(t(scale(t(Fig_QC_PCA_PVCA_HC$CP$Expr.Med.withinBatch.F.BatchCorr))), 
                     name="Z-score",
             col=colorRamp2(c(-4, 0, 4), c("blue","white", "red")),
                     cluster_rows = F, 
             top_annotation = create_heatmapannot(Fig_QC_PCA_PVCA_HC$CP$Annot.Med.withinBatch, annot.columns, colorlist), 
             cluster_columns = T, clustering_distance_columns = "pearson",
             #column_split = 4, 
             show_row_names = F, show_heatmap_legend = T, width  = unit(40, "cm"),
             row_title = NULL,height  = unit(0.01, "cm")),
             annotation_legend_side="bottom")

draw(Heatmap(t(scale(t(Fig_QC_PCA_PVCA_HC$CM$Expr.Med.withinBatch.F.BatchCorr))), 
                     name="Z-score",
             col=colorRamp2(c(-4, 0, 4), c("blue","white", "red")),
                     cluster_rows = F, top_annotation = create_heatmapannot(Fig_QC_PCA_PVCA_HC$CM$Annot.Med.withinBatch, annot.columns, colorlist), 
             cluster_columns = T, clustering_distance_columns = "pearson",
             #column_split = 4, 
             show_row_names = F, show_heatmap_legend = T, width  = unit(40, "cm"),
             row_title = NULL,height  = unit(0.01, "cm")),
             annotation_legend_side="bottom")

```


```{r }

pdf(file="Figures/HC_CP_after_batch_correction.pdf",width = 20, height = 8)
draw(Heatmap(t(scale(t(Fig_QC_PCA_PVCA_HC$CP$Expr.Med.withinBatch.F.BatchCorr))), 
                     name="Z-score",
             col=colorRamp2(c(-4, 0, 4), c("blue","white", "red")),
                     cluster_rows = F, 
             top_annotation = create_heatmapannot(Fig_QC_PCA_PVCA_HC$CP$Annot.Med.withinBatch, annot.columns, colorlist), 
             cluster_columns = T, clustering_distance_columns = "pearson",
             #column_split = 4, 
             show_row_names = F, show_heatmap_legend = T, width  = unit(40, "cm"),
             row_title = NULL,height  = unit(0.01, "cm")),
             annotation_legend_side="bottom")
dev.off()

pdf(file="Figures/HC_CM_after_batch_correction.pdf",width = 20, height = 8)
draw(Heatmap(t(scale(t(Fig_QC_PCA_PVCA_HC$CM$Expr.Med.withinBatch.F.BatchCorr))), 
                     name="Z-score",
             col=colorRamp2(c(-4, 0, 4), c("blue","white", "red")),
                     cluster_rows = F, top_annotation = create_heatmapannot(Fig_QC_PCA_PVCA_HC$CM$Annot.Med.withinBatch, annot.columns, colorlist), 
             cluster_columns = T, clustering_distance_columns = "pearson",
             #column_split = 4, 
             show_row_names = F, show_heatmap_legend = T, width  = unit(40, "cm"),
             row_title = NULL,height  = unit(0.01, "cm")),
             annotation_legend_side="bottom")
dev.off()


```



```{r}
loaded <- load("RData/Fig_secreted.RData")
loaded
```


```{r , fig.width=10, fig.height=6}


p <- ggplot(Fig_secreted, aes(x = CP.Mean, y = CP.SD)) +
    geom_point(alpha=0.5,aes(color = Secretion_info))+ theme_classic() + 
  theme(legend.position = "bottom") + ggtitle("CP") + 
  xlab("Protein mean intensity") + ylab("Protein standard deviation")+
  scale_colour_manual( values=c("1" = "red", "2" = "blue", "3" = "lightgreen", "4" = "grey"))+
  xlim(c(9, 33)) + ylim(c(0,5.5))
p1 <- ggExtra::ggMarginal(p, type = "density", groupFill  = TRUE)


p <- ggplot(Fig_secreted, aes(x = CM.Mean, y = CM.SD)) +
    geom_point(alpha=0.5,aes(color = Secretion_info))+ theme_classic() + 
  theme(legend.position = "bottom")  + ggtitle("CM") + 
  xlab("Protein mean intensity") + ylab("Protein standard deviation")+
  scale_colour_manual( values=c("1" = "red", "2" = "blue", "3" = "lightgreen", "4" = "grey"))+
  xlim(c(9, 33)) + ylim(c(0,5.5))
p2 <- ggExtra::ggMarginal(p, type = "density", groupFill  = TRUE)

g <- ggarrange(p1,p2, ncol=2)
g
ggsave(file="Figures/Secreted_proteins.pdf",g)

```







