---
title: "sPLS-DA"
author: Beata Szeitz
output:
  html_notebook:
    toc: yes
---

# Load packages, functions and files

```{r }
source("Install_load_packages.R")
source("Utility_functions.R")
source("Color_list.R")
```

```{r Load files}
Annot <- read_in_with_rowname("Files/Annotation",F)
row.names(Annot) <- Annot$Sample
CP.expr.imp <- read_in_with_rowname("Files/CP_expression_filtered_imputed",F)[,Annot$Sample]
CM.expr.imp <- read_in_with_rowname("Files/CM_expression_filtered_imputed",F)[,Annot$Sample]
Secreted.proteins <- read_in_with_rowname("Files/Tier1_and_2_secreted",F)[,1]
CM.expr.imp.secr <- CM.expr.imp[row.names(CM.expr.imp) %in% Secreted.proteins,]
```


```{r }
row.names(CP.expr.imp) <- paste(row.names(CP.expr.imp), "CP", sep="_")
row.names(CM.expr.imp.secr) <- paste(row.names(CM.expr.imp.secr), "CM", sep="_")


X.Both <- scale(t(rbind(CP.expr.imp, CM.expr.imp.secr)))
Y <- Annot$Subtype
```


```{r }
pca.Both = pca(X.Both, ncomp = 10, center = TRUE, scale = TRUE)
#pca.srbct #outputs the explained variance per component
plot(pca.Both)  # screeplot of the eingenvalues (explained variance per component)


plotIndiv(pca.Both, group = Y, ind.names = FALSE, 
          legend = TRUE, title = 'PCA on Both')


```

# PLS-DA



```{r }
Both.plsda <- plsda(X.Both, Y, ncomp = 10)  # set ncomp to 10 for performance assessment later
plotIndiv(Both.plsda , comp = 1:2,
          group = Y, ind.names = FALSE, 
          ellipse = TRUE, legend = TRUE, title = 'PLSDA on Both')
plotIndiv(Both.plsda , comp = c(1,3),
          group = Y, ind.names = FALSE, 
          ellipse = TRUE, legend = TRUE, title = 'PLSDA on Both')

```

```{r }
# with background
background = background.predict(Both.plsda, comp.predicted=2, dist = "max.dist") 
#optional: xlim = c(-40,40), ylim = c(-30,30))

plotIndiv(Both.plsda, comp = 1:2,
          group = Y, ind.names = FALSE, title = "Maximum distance",
          legend = TRUE,  background = background)
plotIndiv(Both.plsda, comp = c(1,3),
          group = Y, ind.names = FALSE, title = "Maximum distance",
          legend = TRUE,  background = background)
```


```{r }
# takes a couple of minutes to run
set.seed(2543) # for reproducibility, only when the `cpus' argument is not used
#perf.plsda.Both <- perf(Both.plsda, validation = "Mfold", folds = 3, 
#                  progressBar = T, auc = TRUE, nrepeat = 10) 
#save(perf.plsda.Both, file="RData/perf_plsda_Both.RData")
load("RData/perf_plsda_Both.RData")
# perf.plsda.srbct$error.rate  # error rates
plot(perf.plsda.Both, col = color.mixo(5:7), sd = TRUE, legend.position = "horizontal")
```

```{r }
pdf(file="Figures/PLSDA_performance_plot.pdf",width = 7, height = 5)
plot(perf.plsda.Both, col = color.mixo(5:7), sd = TRUE, legend.position = "horizontal")
dev.off()

```


```{r }
perf.plsda.Both$choice.ncomp
```

# sPLS-DA



```{r }
# grid of possible keepX values that will be tested for each component
list.keepX <- c(1:9,  seq(10, 80, 5))

set.seed(2543) # for reproducibility here,
# to speed up the computational time, consider the cpu argument
#tune.splsda.Both <- tune.splsda(X.Both, Y, ncomp = 5, validation = 'Mfold', 
#                                 folds = 3, 
#                           progressBar = TRUE, dist = 'centroids.dist', measure = "BER",
#                          test.keepX = list.keepX, nrepeat = 50, cpus = 4)
#save(tune.splsda.Both, file="RData/tune_splsda_Both.RData")
load("RData/tune_splsda_Both.RData")
```


```{r }
error <- tune.splsda.Both$error.rate  # error rate per component for the 8 grid

ncomp <- tune.splsda.Both$choice.ncomp$ncomp # optimal number of components based on t-tests
ncomp


select.keepX <- tune.splsda.Both$choice.keepX[1:ncomp]  # optimal number of variables to select
select.keepX
```


```{r }
plot(tune.splsda.Both, col = color.jet(5))

```


```{r }
splsda.Both <- splsda(X.Both, Y, ncomp = ncomp, keepX = select.keepX) 

```


```{r }
plotIndiv(splsda.Both, comp = c(1,2),
          group = Y, ind.names = FALSE, 
          ellipse = TRUE, legend = TRUE,
          title = 'sPLS-DA, comp 1 & 2')

plotIndiv(splsda.Both, comp = c(1,3),
          group = Y, ind.names = FALSE, 
          ellipse = TRUE, legend = TRUE,
          title = 'sPLS-DA, comp 1 & 3')

```


```{r }
pdf(file="Figures/sPLSDA_components12.pdf",width = 7, height = 5)
plotIndiv(splsda.Both, comp = c(1,2),
          group = Y, ind.names = FALSE, 
          ellipse = TRUE, legend = TRUE,
          title = 'sPLS-DA, comp 1 & 2')
dev.off()

pdf(file="Figures/sPLSDA_components13.pdf",width = 7, height = 5)
plotIndiv(splsda.Both, comp = c(1,3),
          group = Y, ind.names = FALSE, 
          ellipse = TRUE, legend = TRUE,
          title = 'sPLS-DA, comp 1 & 3')
dev.off()

```



```{r }
set.seed(40) # for reproducibility, only when the `cpus' argument is not used
# takes about 1 min to run
#perf.Both <- perf(splsda.Both, validation = "Mfold", folds = 3,
#                  dist = 'centroids.dist', nrepeat = 100, cpus = 2,
#                   progressBar = T) 
#save(perf.Both, file="RData/splsda_perf_Both.RData")
load("RData/splsda_perf_Both.RData")

```



```{r }
# perf.srbct  # lists the different outputs
perf.Both$error.rate

plot(perf.Both, col = color.mixo(5))
```

```{r }
pdf(file="Figures/sPLSDA_classification_perf.pdf",width = 7, height = 5)
plot(perf.Both, col = color.mixo(5))
dev.off()
```


```{r }
par(mfrow=c(1,3))
plot(perf.Both$features$stable[[1]], type = 'h', ylab = 'Stability', 
     xlab = 'Features', main = 'Comp 1', las =2)
plot(perf.Both$features$stable[[2]], type = 'h', ylab = 'Stability', 
     xlab = 'Features', main = 'Comp 2', las =2)
plot(perf.Both$features$stable[[3]], type = 'h', ylab = 'Stability', 
     xlab = 'Features', main = 'Comp 3', las =2)

```


# Collect the selected proteins and export


```{r }
# here we match the selected variables to the stable features
ind.match = match(selectVar(splsda.Both, comp = 1)$name, 
                  names(perf.Both$features$stable[[1]]))
#extract the frequency of selection of those selected variables
Freq = as.numeric(perf.Both$features$stable[[1]][ind.match])

#data.frame(selectVar(splsda.Both, comp = 1)$value, Freq)

Both.comp1.selected <- data.frame(selectVar(splsda.Both, comp = 1)$value, Freq)

Both.comp1.selected$Rank <- Both.comp1.selected$value.var * Both.comp1.selected$Freq
Both.comp1.selected$Sign <- ifelse(Both.comp1.selected$Rank > 0, "pos", "neg")
Both.comp1.selected$Comp <- 1
Both.comp1.selected$Accession <- row.names(Both.comp1.selected)

Both.comp1.selected <- Both.comp1.selected[order(abs(Both.comp1.selected$Rank), decreasing = T),]

Both.comp1.selected

```

```{r }
# here we match the selected variables to the stable features
ind.match = match(selectVar(splsda.Both, comp = 2)$name, 
                  names(perf.Both$features$stable[[2]]))
#extract the frequency of selection of those selected variables
Freq = as.numeric(perf.Both$features$stable[[2]][ind.match])

#data.frame(selectVar(splsda.Both, comp = 2)$value, Freq)

Both.comp2.selected <- data.frame(selectVar(splsda.Both, comp = 2)$value, Freq)
Both.comp2.selected$Rank <- Both.comp2.selected$value.var * Both.comp2.selected$Freq
Both.comp2.selected$Sign <- ifelse(Both.comp2.selected$Rank > 0, "pos", "neg")
Both.comp2.selected$Comp <- 2
Both.comp2.selected$Accession <- row.names(Both.comp2.selected)

Both.comp2.selected <- Both.comp2.selected[order(abs(Both.comp2.selected$Rank), decreasing = T),]

Both.comp2.selected

```




```{r }
# here we match the selected variables to the stable features
ind.match = match(selectVar(splsda.Both, comp = 3)$name, 
                  names(perf.Both$features$stable[[3]]))
#extract the frequency of selection of those selected variables
Freq = as.numeric(perf.Both$features$stable[[3]][ind.match])

#data.frame(selectVar(splsda.Both, comp = 3)$value, Freq)

Both.comp3.selected <- data.frame(selectVar(splsda.Both, comp = 3)$value, Freq)
Both.comp3.selected$Rank <- Both.comp3.selected$value.var * Both.comp3.selected$Freq
Both.comp3.selected$Sign <- ifelse(Both.comp3.selected$Rank > 0, "pos", "neg")
Both.comp3.selected$Comp <- 3
Both.comp3.selected$Accession <- row.names(Both.comp3.selected)

Both.comp3.selected <- Both.comp3.selected[order(abs(Both.comp3.selected$Rank), decreasing = T),]

Both.comp3.selected

```


```{r }
plotLoadings(splsda.Both, comp = 1, title = 'Loadings on comp 1', 
             contrib = 'max', method = 'median')
plotLoadings(splsda.Both, comp = 2, title = 'Loadings on comp 2', 
             contrib = 'max', method = 'median')
plotLoadings(splsda.Both, comp = 3, title = 'Loadings on comp 3', 
             contrib = 'max', method = 'median')
plotLoadings(splsda.Both, comp = 1, title = 'Loadings on comp 1', 
             contrib = 'max', method = 'mean')
plotLoadings(splsda.Both, comp = 2, title = 'Loadings on comp 2', 
             contrib = 'max', method = 'mean')
plotLoadings(splsda.Both, comp = 3, title = 'Loadings on comp 3', 
             contrib = 'max', method = 'mean')
```

```{r }
plotArrow(splsda.Both, legend=T)
plotVar(splsda.Both)
```



```{r }

hist(Both.comp1.selected$Rank)
hist(Both.comp1.selected$Rank)

nrow(Both.comp1.selected[abs(Both.comp1.selected$Rank) > 0.1,])
Both.comp1.selected[abs(Both.comp1.selected$Rank) > 0.1,]

nrow(Both.comp2.selected[abs(Both.comp2.selected$Rank) > 0.1,])
Both.comp2.selected[abs(Both.comp2.selected$Rank) > 0.1,]

Both.comp3.selected

```


```{r }
Both.comp.selected <- rbind(Both.comp1.selected, Both.comp2.selected, Both.comp3.selected)

export_with_rowname(Both.comp.selected, "Files/sPLSDA_results",F)

```
